version: '3.8'
services:
  hidream:
    build: .
    ports:
      - "8000:8000"
      - "7860:7860"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped